### ISSUE TITLE
Design and Implement meta-data spec

### ISSUE THREAD

**Issue by AndrewOfC** [AndrewOfC/ucompleter#3]
To allow the use of this tool with multiple applications, implement a meta-data block that will describe the following:

1. The root element that describes where potential completions will be found
2. A terminus key that will indicate where completions end.  (i.e. if this key exists in the current block, stop descending)

Example:

```yaml
meta-data:
    root:  root
    terminus:  address

root:
    registers:
        gpio0:
            description: |
                 GPIO 0  Write a 1 to pull pin hi, a 0 to pull pin low

            address:  0x00000

```
